- name: farend_basic theme download
  become: yes
  git:
    repo=https://github.com/farend/redmine_theme_farend_basic.git
    dest={{ redmine_dir }}/public/themes/farend_basic

- name: flat_theme theme download
  become: yes
  git:
    repo=https://github.com/ssaito/redmine-theme-flat.git
    dest={{ redmine_dir }}/public/themes/redmine_flat

- name: theme_gitmike theme download
  become: yes
  git:
    repo=https://github.com/makotokw/redmine-theme-gitmike.git
    dest={{ redmine_dir }}/public/themes/gitmike

- name: flatly_light theme download
  become: yes
  git:
    repo=https://github.com/Nitrino/flatly_light_redmine.git
    dest={{ redmine_dir }}/public/themes/flatly_light_redmine

- name: theme_purplemine2 theme download
  become: yes
  git:
    repo={{ redmine_theme_purplemine2_repo }}
    dest={{ redmine_dir }}/public/themes/PurpleMine2

- name: theme_kodomo
  become: yes
  git:
    repo=https://github.com/akiko-pusu/redmine_theme_kodomo.git
    dest={{ redmine_dir }}/public/themes/kodomo

- name: theme_kodomo_midori
  become: yes
  git:
    repo=https://github.com/akiko-pusu/redmine_theme_kodomo_midori.git
    dest={{ redmine_dir }}/public/themes/redmine_theme_kodomo_midori

- name: farend_bleuclair_check
  stat:
    path: "{{ redmine_dir }}/public/themes/bleuclair"
  register: bleuclair_chk_file

- name: farend_bleuclair
  become: yes
  git:
    repo=https://github.com/farend/redmine_theme_farend_bleuclair.git
    dest={{ redmine_dir }}/public/themes/bleuclair
  when: bleuclair_chk_file.stat.exists == false

- name: redmine_theme_minimalflat2_download
  become: yes
  get_url:
    url: https://github.com/akabekobeko/redmine-theme-minimalflat2/releases/download/v1.7.0/minimalflat2-1.7.0.zip
    dest: /tmp

- name: redmine_theme_minimalflat2_dir
  become: yes
  file: path={{ redmine_dir }}/public/themes/minimalflat2 state=directory owner=root group=root mode=0755

- name: redmine_theme_minimalflat2_extract
  become: yes
  unarchive: src=/tmp/minimalflat2-1.7.0.zip dest={{ redmine_dir }}/public/themes

- name: default_theme
  become: yes
  command:
    bundle exec rails r 'Setting["ui_theme"]="{{ redmine_default_theme }}"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
